# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Theme name
theme = "no-style-please"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

# Additional languages definition

## Spanish
[languages.es]

[extra]
# Put all your custom variables here

# Enable listing of pages in homepage
list_pages = true
